### ISSUE TITLE
Video player(s)

### ISSUE THREAD

**Issue by tbeddy** [maggieyam/menutube#5]
So I'm thinking that our main video player (the "kitchen" as I was calling it) would be the central part of our dashboard/hub. It would have the basic controls that come baked into `react-player` like play/pause, seeking different parts of the video, and a full screen button. An extra important feature would be timestamps, like on YouTube, which would allow users to move to when each step in the recipe takes place. Alternatively, we could just have all of this in each video's show page.

For a list of videos, either as a user's feed or through searching tags, I was thinking that we wouldn't show the timestamps so as not to clutter up the space (but show them of course if they were to play one of these videos in the kitchen/show page). We would probably only allow one video to be playing at a time, so we could keep the current video's id in state. We might not have the full screen button for these videos to keep the user focused on the feed.

**Comment by tabemono** [comment]
CSS DAY  possibly and combining most of our features today.

**Comment by tbeddy** [comment]
Mostly wrapped up. Timestamp work and tags can be discussed in a different issue.
