### ISSUE TITLE
Fix bugginess of the splash page

### ISSUE THREAD

**Issue by tbeddy** [maggieyam/menutube#68]
In Rosemary's words: "The splash page seems very buggy; usually I see only the orange background with the mixing bowl background on the page, but I sometimes see what looks like more of a splash page (additional color-blocked sections with sample videos) when I scroll down. But the view is very inconsistent. Sometimes when I scroll down to the video portion of the splash page, I'm unable to scroll all the way back up to the top."

**Comment by tabemono** [comment]
awaiting Rosemary response

**Comment by tbeddy** [comment]
We scrapped most of the splash page for now, so that's a kind of a fix.
